version: "3"
services:
  api:
    build: .
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    command: mongod --port 27017
    volumes:
      # instead map path directory -> map name volumes with directory
      - mongo-db:/data/db
volumes:
  mongo-db:
    
   
  