version: '3.8'
services:
  api:
    build:
        context: .
        args:
          - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm run prod"
    
    
     
    
     