version: "3"
services:
  api:
    build: .
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # instead map path directory -> map name volumes with directory
      - mongo-db:/data/db
volumes:
  mongo-db:
    
   
  